### ISSUE TITLE
Crash with exit code 1

### ISSUE THREAD

**Issue by WordStormRose** [Nyfaria/DynamicSurroundingsResurrected#1]
Good day!

I tried to add this to the 1.18.2 version of my modpack, but when I try to load the game it crashes with Exit Code 1 (which speaks of "invalid Java runtime configuration"); removing Dynamic Surroundings Resurrected allows the game to load correctly. 
I'd attach the crash report, but it didn't give me one.

Edit: forge version is 40.1.41; other mods in my pack have issues with newer versions of forge for reasons unknown.

**Comment by Nyfaria** [comment]
fixed in an updated
