### ISSUE TITLE
Footprints missing with Rubidium/Oculus.

### ISSUE THREAD

**Issue by Orgamorsh** [Nyfaria/DynamicSurroundingsResurrected#4]
The footprints from the original Dynamic Surroundings seem to be missing. I don't know if it because I am on a server or if it just not a thing yet.

**Comment by Nyfaria** [comment]
Footprints are working, you might have a mod that interferes

**Comment by Orgamorsh** [comment]
Ok, so this is a incompatibility with rubidium and oculus.

**Comment by Nyfaria** [comment]
> Ok, so this is a incompatibility with rubidium and oculus.

Shaders and Fake optimization mods tend to mess up rendering. This isn't really a fixable issue.
