### ISSUE TITLE
[Bug] DynamicSurroundings-5.0.0.4.jar Crashes with Additional Structures

### ISSUE THREAD

**Issue by SirChamomile** [Nyfaria/DynamicSurroundingsResurrected#7]
Using Rex's-AdditionalStructures-1.18.2-(v.3.1.0).jar causes a crash during initialization. Isolated to just these two mods.

[crash-2022-06-15_16.21.20-client.txt](https://github.com/Nyfaria/DynamicSurroundingsResurrected/files/8913248/crash-2022-06-15_16.21.20-client.txt)

**Comment by Nyfaria** [comment]
update your forge version
