### ISSUE TITLE
[Bug] DynamicSurroundings-5.0.0.4.jar Crashes with Iceberg

### ISSUE THREAD

**Issue by SirChamomile** [Nyfaria/DynamicSurroundingsResurrected#8]
Using Iceberg-1.18.2-1.0.44.jar causes a crash during initialization. Isolated to just these two mods. Iceberg is a library mod for Merchant Markers, but just library mod causes the crash.

[crash-2022-06-15_16.25.28-client.txt](https://github.com/Nyfaria/DynamicSurroundingsResurrected/files/8913280/crash-2022-06-15_16.25.28-client.txt)

**Comment by SirChamomile** [comment]
This is also the case with the mod [terraincognita-1.18.2-2.0-BETA3] (https://www.curseforge.com/minecraft/mc-mods/terraincognita/files/3833932). I will isolate and make another issue tomorrow, it's the same crash though.

**Comment by Nyfaria** [comment]
Update your Forge to the newest 1.18.2 version
