### ISSUE TITLE
Certain biome sounds do not stop during serene seasons winter

### ISSUE THREAD

**Issue by IceaPlayzPC** [Nyfaria/DynamicSurroundingsResurrected#9]
in the 1.16 version of dynamic surroundings, whenever it was winter in serene seasons things like birdsong and crickets would cease entirely, and the breath particles would appear, however now that doesn't seem to be the case in 1.18.2 with the birds still singing their hearts away in the dead of winter. Note that i have no idea if this is a dynamic surroundings thing or a serene seasons issue,

steps to reproduce: download serene seasons, change it to winter with /season set and listen to the sounds still playing

Not a game breaking issue of course, but a fairly immersion breaking one as winter is usually silent.

**Comment by IceaPlayzPC** [comment]
After some research i've come to find that the feature i'm talking about appears to have been removed from this fork of the mod. Is there a chance that the serene seasons integration could be re-added?

**Comment by IceaPlayzPC** [comment]
(dont mind me being tired and accidentally closing this, sorry bout that)

**Comment by Nyfaria** [comment]
It might be added back someday, right now I am working on other things.

**Comment by IceaPlayzPC** [comment]
Good to know! I'm excited for when/if it does return c:
